// Component-preload placeholder to avoid 404 and MIME issues
// This file intentionally left minimal for development with ui5 serve.
// In production builds, the real Component-preload will be generated by the build tools.
